name: Container building/publishing

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '33 0 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    environment: main
     
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ vars.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}


      - name: Build container image; push if not pull request
        id: build-push
        env:
          BUILD_REPOSITORY: ${{ vars.REGISTRY }}/${{ env.IMAGE_NAME }}
          BUILD_VERSION: ${{ github.event.head_commit.id }}
          ENABLE_PUSH: ${{ github.event_name != 'pull_request' && '1' || '' }}
        run:
          ./ci.sh

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        if: ${{github.event_name != 'pull_request' && vars.REGISTRY == 'docker.io'}}
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: ${{ env.IMAGENAME }}
