name: Update Dockerhub description

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  push:
    branches: [ "main" ]

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  update-description:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    environment: main
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update Docker Hub description
        uses: peter-evans/dockerhub-description@v4
        if: ${{github.event_name != 'pull_request' && vars.REGISTRY == 'docker.io'}}
        with:
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          repository: ${{ env.IMAGENAME }}

